#!/bin/bash

# symlinked from ~/.githooks/prepare-commit-msg

# uncomment to disable this check
# exit 0

# uncomment to check if it's working
# echo "commit hook encountered!"
# exit 1

if git remote -v | grep -q 'tomwarner13'; then
  if [[ "$GIT_AUTHOR_EMAIL" != "tomwarner13@gmail.com" ]]; then
    echo "Hey dummy! This appears to be a personal repo, and the commit email is not the personal email. Try fixing the email config and trying again."
    echo "git config user.email tomwarner13@gmail.com"
    exit 1
  fi
fi

current_path="$(pwd)"
if [[ "$current_path" = "/c/DealerOn/Projects"* ]]; then
  exit 0
fi


MESSAGE=$(cat $1)
BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ $BRANCH =~ v[0-9]+\. ]]; then
  # this looks like a version branch, meaning we're in the integrate script: exit
  echo "we are apparently on a version branch, bypassing commit message check"
  exit 0
fi

TICKET=$(echo "$BRANCH" | grep -Eo ^[A-Z]+\-[0-9]+)

if [[ -z $TICKET ]]
then
  
  # Allows us to read user input below, assigns stdin to keyboard
  exec < /dev/tty

  echo "Unable to prepend ticket number from branch. Make sure you're not on main."
  echo "Commit anyway? [y for yes, {any} for no]"
  read -p "Commit anyway? " yn
  case $yn in
    [Yy]* ) exit 0;;
    * ) exit 1;;
  esac

  # return input to wherever it was assigned before i guess
  exec <&-
else
  echo "$TICKET: $MESSAGE" > $1
fi
